services:
  nextjs-landing:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: green-company-landing-page
    ports:
      - "3026:3000"
    restart: unless-stopped
    volumes:
      - ./prisma/dev.db:/app/prisma/dev.db